name: 'Bygg og deploy branch til test environment'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which test environment to deploy the branch to'
        default: q2
        required: true

jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v6

      - name: 'Setter dato og commit variabel'
        run: |        
          export TZ=CET
          echo "DATE=$(date '+%Y-%m-%d--%H-%M-%S')" >> $GITHUB_ENV
          echo "GIT_COMMIT=$(echo ${{github.sha}} | cut -c 1-7)" >> $GITHUB_ENV
          echo "GIT_BRANCH=$(echo ${{github.ref_name}})" >> $GITHUB_ENV

      - name: 'Configure git reference tag'
        run: |
          echo "GIT_REF_TAG=git_${GIT_BRANCH}_${GIT_COMMIT}" >> $GITHUB_ENV

      - name: 'Java 21'
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@v5

      - name: 'Generate and submit dependency graph'
        uses: gradle/actions/dependency-submission@v5

      - name: 'Build artifact'
        run: |
          ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push docker image'
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: pensjonopptjening
          tag: ${{env.GIT_REF_TAG}}

      - name: 'Upload test results'
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: failed-test-results
          path: build/reports/tests/test

      - name: 'Deploy pensjon-opptjening-filadapter to dev-fss (Q2)'
        uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: nais/dev-fss-${{ github.event.inputs.environment }}.yml
          CLUSTER: dev-fss
          IMAGE: ${{ steps.docker-push.outputs.image }}
          TELEMETRY: ${{ steps.docker-push.outputs.telemetry }}